services:
  web:
    build: ./backend/customerManager
    command: gunicorn customerManager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/customerManager:/customers
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Assignment

volumes:
  postgres_data:
