services:
  db:
    image: postgres:15
    container_name: assignment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: assignment
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/customerManager
      dockerfile: Dockerfile
    container_name: assignment-backend
    command: gunicorn customerManager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/Assignment
      DJANGO_SETTINGS_MODULE: customerManager.settings
      PYTHONUNBUFFERED: 1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assignment-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
