name: CD

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    name: Build and push container
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}
      
      - name: Set image tag
        id: set-tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "image-tag=${VERSION}" >> $GITHUB_OUTPUT
          else
            SHA=$(echo $GITHUB_SHA | cut -c1-7)
            echo "image-tag=sha-${SHA}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend/customerManager
          file: ./backend/customerManager/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.ACR_REGISTRY }}/customer-manager:${{ steps.set-tag.outputs.image-tag }}
            ${{ secrets.ACR_REGISTRY }}/customer-manager:latest
          cache-from: type=registry,ref=${{ secrets.ACR_REGISTRY }}/customer-manager:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_REGISTRY }}/customer-manager:buildcache,mode=max

  deploy:
    name: Deploy to Azure Container App
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: production
      url: ${{ steps.deploy.outputs.container-app-url }}
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Upload secrets to Azure Container App
        run: |
          az containerapp secret set \
            --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --secrets \
            django-secret-key="${{ secrets.DJANGO_SECRET_KEY }}" \
            postgres-db="${{ secrets.POSTGRES_DB }}" \
            postgres-user="${{ secrets.POSTGRES_USER }}" \
            postgres-password="${{ secrets.POSTGRES_PASSWORD }}" \
            postgres-host="${{ secrets.POSTGRES_HOST }}" \
            postgres-port="${{ secrets.POSTGRES_PORT }}"
  
      - name: Deploy to Azure Container App
        id: deploy
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          imageToDeploy: ${{ secrets.ACR_REGISTRY }}/customer-manager:${{ needs.build-and-push.outputs.image-tag }}
          revisionSuffix: "stable"
          environmentVariables: |
            DEBUG=True
            DJANGO_SECRET_KEY=secretref:django-secret-key
            POSTGRES_DB=secretref:postgres-db
            POSTGRES_USER=secretref:postgres-user
            POSTGRES_PASSWORD=secretref:postgres-password
            POSTGRES_HOST=secretref:postgres-host
            POSTGRES_PORT=secretref:postgres-port
